# Generated by Django 5.1.4 on 2024-12-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0002_telegramuser_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='extra_info',
        ),
    ]
